// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

void onIotCliInOutChange();

String iot_cli_InOut;

void initProperties(){

  ArduinoCloud.addProperty(iot_cli_InOut, READWRITE, ON_CHANGE, onIotCliInOutChange);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

// #error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
